### ISSUE TITLE
Does not work with Remix 2.5.1: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by rustyx** [jacob-ebey/remix-ssg#21]
I try the "[Quick Start](https://remix-ssg.pages.dev/docs/quick-start)" steps...

```none
$ npx create-remix@latest
```
```none
$ cd my-remix-app/
```
```none
$ npm install -D remix-ssg serve
```
```none
$ cat <<"EOM" >>app/routes/_index.tsx

export function getStaticPaths() {
  return ["/"];
}
EOM
```
and it fails:

```none
$ remix-ssg public
 info  building... (NODE_ENV=production)
 info  built (181ms)
Generating 1 static HTML pages...
file:///home/user/my-remix-app/node_modules/remix-ssg/lib/cli.mjs:80
      for (const [routeId, routeData] of Object.entries(
                                                ^

TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at file:///home/user/my-remix-app/node_modules/remix-ssg/lib/cli.mjs:80:49
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/user/my-remix-app/node_modules/remix-ssg/lib/cli.mjs:12:1
```

```none
$ npm ls
my-remix-app@ /home/user/my-remix-app
├── @remix-run/css-bundle@2.5.1
├── @remix-run/dev@2.5.1
├── @remix-run/node@2.5.1
├── @remix-run/react@2.5.1
├── @remix-run/serve@2.5.1
├── @types/react-dom@18.2.18
├── @types/react@18.2.48
├── @typescript-eslint/eslint-plugin@6.19.1
├── eslint-config-prettier@9.1.0
├── eslint-import-resolver-typescript@3.6.1
├── eslint-plugin-import@2.29.1
├── eslint-plugin-jsx-a11y@6.8.0
├── eslint-plugin-react-hooks@4.6.0
├── eslint-plugin-react@7.33.2
├── eslint@8.56.0
├── isbot@4.4.0
├── react-dom@18.2.0
├── react@18.2.0
├── remix-ssg@0.0.8
├── serve@14.2.1
└── typescript@5.3.3
```

**Comment by imki123** [comment]
me too

**Comment by rustyx** [comment]
Forget about this - the project is long abandoned..
